# Generated by Django 4.2.3 on 2023-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frauddetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('followers', models.IntegerField()),
                ('follows', models.IntegerField()),
                ('descrpt', models.CharField(max_length=500)),
                ('profile', models.CharField(max_length=10)),
                ('private', models.CharField(max_length=10)),
            ],
        ),
    ]
